steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'curl'
  args: ['-L', '-o', '/workspace/dictionary.csv', 'https://raw.githubusercontent.com/jiayuchann/GCP-test/main/dictionary.csv']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: ['load', '--autodetect', '--replace', '--source_format=CSV', 'bigquery-stuff-389701:sre.dictionary', '/workspace/dictionary.csv']

options:
  logging: CLOUD_LOGGING_ONLY
