steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['curl', '-L', '-o', '/workspace/dictionary.csv', 'https://raw.githubusercontent.com/jiayuchann/GCP-test/main/your_csv_file.csv']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['bq', 'load', '--autodetect', '--replace', '--source_format=CSV', 'bigquery-stuff-389701:sre.dictionary', '/workspace/dictionary.csv']
